### ISSUE TITLE
divider 宽度计算不准确，导致UI错位

### ISSUE THREAD

**Issue by Justin-lu** [alibaba-fusion/layout#13]
详细图片如下：

![image](https://user-images.githubusercontent.com/1632249/222366520-80dfe671-d3e0-4e9a-9929-43045bf5ab30.png)

![image](https://user-images.githubusercontent.com/1632249/222366698-cf66555a-03ad-4dea-a3cb-dfa0eabae3f2.png)

初步定位问题：https://github.com/alibaba-fusion/layout/blob/next/lowcode/common/divider.tsx#L90

```js
    const rect = selectedNode.getRect();
```

rect 拿到的 width 不准确

**Comment by bindoon** [comment]
交互形式可以说下。
比如是否是：刚刚垂直切割完后，鼠标正好hover右侧面板，计算时机比较早！

**Comment by Justin-lu** [comment]
```js
  const onSelectionChange = useCallback((timer = 100) => {
    setDisabled(false);

    const selectedNode = getSelectedNode(engine.current);
    if (!selectedNode) {
      setCuts([]);
      return;
    }

    // TODO
    // 目前 selectionChang 时 dom 结构可能还在变化
    // 会偶尔导致 computCuts 计算尺寸出现问题，需要优化
    if (timer) {
      setTimeout(() => {
        computCuts(selectedNode);
      }, timer);
    } else {
      computCuts(selectedNode);
    }
  }, []);

  useEffect(() => {
    const { project } = engine.current;
    if (!project) return;

    project.currentDocument?.onChangeSelection(onSelectionChange);
  }, []);



  const onEnabled = useCallback(() => {
    setDisabled(false);
    onSelectionChange(0);
  }, [onSelectionChange]);
```

看了一下代码，这里的 回调 有点问题，手动调用的时候 `onSelectionChange(0)` timer是正常的
但是在 onChangeSelection 调用时，由于回调函数会默认参数传入（与timer混淆），导致timer=100默认值无效
调试逻辑如下：
![image](https://user-images.githubusercontent.com/1632249/222370899-4aec0ed3-3c4d-4945-8ed3-e01bcb8e3a70.png)

![image](https://user-images.githubusercontent.com/1632249/222370837-7ada22ac-448e-4572-98e2-e36dc5d02e7a.png)

**Comment by Justin-lu** [comment]
补充下回调声明：

```typescript
/**
 * 当前 document 的选中变更事件
 * set callback for event on selection changed
 */
onChangeSelection(fn: (ids: string[]) => void): IPublicTypeDisposable;
```

**Comment by silinchen** [comment]
#14 pr已解决这个问题
