### ISSUE TITLE
拖拽修改容器高度，导致容器变空白

### ISSUE THREAD

**Issue by silinchen** [alibaba-fusion/layout#23]
拖拽修改容器高度，会将容器内占位的内容去掉，与修改宽度交互不一致，修改宽度的时候不会去掉容器内占位内容。

![image](https://user-images.githubusercontent.com/17904619/223312387-397f7537-fe81-42e1-b9d7-186b8d22279a.png)

拖拽时，会修改容器的 minHeight 属性

layout/lowcode/metas/enhance/callbacks.ts

```typescript
currentNode.setPropValue('style.minHeight', newHeight);
```

渲染时，会判断如果有 minHeight 属性，则不显示占位内容

layout/lowcode/view.tsx

```typescript
let newChildren = children;
if (!children?.length && !props.style?.minHeight) {
  newChildren = <div className="lc-container-placeholder">拖拽组件或模板到这里</div>;
}
```

重现方法：
将容器上下分割后，拖拽修改容器高度。

**Comment by bindoon** [comment]
可以先按照你的思路来解决，之前这么写的原因是设置了 minHeight 但是因为有占位高度导致最小高度没变化 @silinchen
